version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd basic-react && npm start"
    ports:
      - "3000:3000"
    stdin_open: true
